FROM php:7.4-fpm

RUN apt-get update && apt-get install -y \
	unzip \
	git \
	curl \
	libzip-dev \
	&& docker-php-ext-install zip pdo pdo_mysql \
	&& pecl install redis \
	&& docker-php-ext-enable redis

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN chown -R www-data:www-data /var/www/html

EXPOSE 9000

CMD ["php-fpm"]